name: taravel2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

  flutter_svg: ^2.0.10+1
  syncfusion_flutter_datepicker: ^25.1.42
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: Outfit
    fonts:
      - asset: fonts/Outfit-Regular.ttf
        weight: 400
